# Generated by Django 5.0.6 on 2024-05-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authpage', '0004_rename_user_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
