# Generated by Django 5.0.6 on 2024-05-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authpage', '0006_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
