# Generated by Django 5.0.6 on 2024-05-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authpage', '0008_alter_userinfo_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
